name: yelp_fusion_client
version: 0.2.0+4-hotfix

description: A Dart Client to access the business endpoints of Yelp Fusion API.
homepage: https://github.com/VolodymyrKos/yelp_fusion_client

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  http: ^1.1.0